apiVersion: v1
kind: Service
metadata:
  name: nlp-api-service  # Simplified name
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000  # Optional: fix for testing
  selector:
    app: nlp-api