FROM python:3.10-slim

# System deps
RUN apt-get update && apt-get install -y git && apt-get clean

# Create app dir
WORKDIR /app

# Copy code + requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

# Expose port and run
EXPOSE 8001
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
